const services=[
 {name:'Car Decors',desc:'Wedding car decoration, vehicle styling and celebration-ready finishing touches.',folder:'CAR DECORS-20260923T073821Z-1-001/CAR DECORS',files:['IMG_6981.MOV','IMG_6982.MOV','IMG_7205.MOV','copy_11267627-C801-41AF-8F51-B6BDECB6D47E.MOV','copy_B62811C3-0B0D-47F3-9C75-FDD6A7CDA5F2.MOV','IMG_3817.MOV','copy_E8ECCF8F-959F-4282-934F-AF11D470F77D.MOV'],symbol:'✳'},
 {name:'Catering',desc:'Food arrangements and catering for weddings, parties and special occasions.',folder:'CATERING -20260923T070655Z-1-001/CATERING',files:['CATERING.MP4','CATERING(1).MP4','CATERING.MOV'],symbol:'✳'},
 {name:'Dress Shop',desc:'Wedding outfits, occasion wear and thoughtful styling for the moments you’ll remember.',folder:'DRESS SHOP-20260923T070659Z-1-001/DRESS SHOP',files:['MEDIA SPACE 1.MOV','MEDIA SPACE 3.MOV','MEDIA SPACE 5.MOV','MEDIA SPACE 6.MOV','copy_F3D72ED4-0A98-4E60-9654-99C4A8B3406E.MOV','MEDIA SPACE 2.MOV','copy_6EA08C48-83D5-4F42-B1F2-2DB4AF776FDC.MOV','MEDIA SPACE 4.MOV','MEDIA SPACE 7.MOV'],symbol:'✳'},
 {name:'Holidays',desc:'Holiday planning, travel experiences and celebration trips to look forward to.',folder:'HOLIDAYS-20260923T070701Z-1-001/HOLIDAYS',files:['HOLIDAYS 1.MOV','HOLIDAY 2.MOV'],symbol:'✳'},
 {name:'Personal Booking',desc:'Personal appointments and booking enquiries to help bring your plans together.',folder:'PERSONAL BRANDING -20260923T070703Z-1-001/PERSONAL BRANDING',files:['MEDIA SPACE.MOV'],symbol:'✳'},
 {name:'Saloon',desc:'Beauty, grooming and styling services for your special occasion.',folder:'SALOON-20260923T070706Z-1-001/SALOON',files:['IMG_3406.MOV','IMG_3388.MOV','IMG_1041.MOV'],symbol:'✳'}
];
const appBase=new URL('./',location.href);const assetUrl=path=>new URL(path,appBase).href;
const browserVideo=file=>file.toLowerCase().endsWith('.mov')?`${file.slice(0,-4)}.mp4`:file;
const media=s=>assetUrl(`video/${encodeURIComponent(browserVideo(s.files[0]))}`);
const poster=s=>assetUrl(s.name==='Dress Shop'?'image/ChatGPT%20Image%20Sep%2024,%202026,%2002_17_50%20PM.png':'image/IMG_5280.PNG');
const grid=document.querySelector('#service-grid');
const gymService={name:'Gym',desc:'Gym training and fitness sessions.'},jewellerService={name:'Kavitha Jewellers',desc:'A look at jewellery and designs from Kavitha Jewellers.'};
grid.innerHTML=[gymService,jewellerService,...services].map((s,i)=>{const src=s.name==='Gym'?assetUrl('video/IMG_6664.mp4'):s.name==='Kavitha Jewellers'?assetUrl('video/IMG_6674.MP4'):media(s);return `<article class="service-card"><div class="service-media play-media" style="--poster:url('${poster(s)}')" data-poster="${poster(s)}" data-src="${src}" data-title="${s.name}" role="group" aria-label="${s.name} video"><span class="poster-label">${s.name}<small>MEDIA SPACE · ${String(i+1).padStart(2,'0')}</small></span><button class="play-icon" type="button" aria-label="Play ${s.name} video">▶</button><span class="card-index">${String(i+1).padStart(2,'0')}</span></div><div class="service-body"><div><h3>${s.name}</h3><p>${s.name==='Car Decors'?'Wedding car styling and festive finishing touches.':s.desc}</p></div><a href="#booking" class="service-link" ${['Gym','Kavitha Jewellers'].includes(s.name)?'':'data-service="'+s.name+'"'} aria-label="Enquire about ${s.name}">↗</a></div></article>`}).join('');
function createPreview(tile){if(tile.querySelector('video'))return tile.querySelector('video');const v=document.createElement('video');v.className='inline-player';v.muted=true;v.defaultMuted=true;v.autoplay=true;v.loop=true;v.playsInline=true;v.preload='none';v.poster=tile.dataset.poster||'';v.setAttribute('aria-label',`${tile.dataset.title} muted video preview`);v.addEventListener('loadedmetadata',()=>{if(v.videoWidth&&v.videoHeight)tile.style.setProperty('--video-ratio',`${v.videoWidth} / ${v.videoHeight}`)},{once:true});v.src=tile.dataset.src;v.addEventListener('error',()=>{if(!tile.querySelector('.playback-error')){const note=document.createElement('span');note.className='playback-error';note.textContent='Preview unavailable on this device. Tap to try playback.';tile.append(note)}},{once:true});tile.append(v);return v}
function observePreviews(scope=document){if(!('IntersectionObserver'in window)){scope.querySelectorAll('.play-media').forEach(createPreview);return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const tile=entry.target;if(entry.isIntersecting){const v=createPreview(tile);if(!v.dataset.userPlayback)v.play().catch(()=>{})}else tile.querySelector('video')?.pause()}),{rootMargin:'100px 0px',threshold:.15});scope.querySelectorAll('.play-media').forEach(tile=>observer.observe(tile))}
observePreviews(grid);
const wedding=[
 {name:'Wedding Package 1',price:'₹45,999',items:['Traditional photo','Traditional video','12×36 album · 30 sheets','2 calendars']},
 {name:'Wedding Package 2',price:'₹69,999',items:['Traditional photo','Traditional video','Candid photo','Candid video','12×36 album · 35 sheets','2 calendars']},
 {name:'Wedding Package 3',price:'₹99,999',items:['Traditional photo','Traditional video','Candid photo','Candid video','Drone shot · engagement or marriage','12×36 premium album','2 calendars','2 frames']}
], other=[
 {name:'Event Package 1',price:'₹14,999',items:['Traditional photo','12×36 album · 20 sheets']},
 {name:'Event Package 2',price:'₹34,999',items:['Traditional photo','Candid video','12×36 album · 20 sheets']}
], social=[
 {name:'Basic',price:'₹19,999',items:['10 feed posts per month','Content caption writing','5 feed posters','Post scheduling','Hashtag research','Instagram handling']},
 {name:'Standard',price:'₹39,999',items:['20 feed posts per month','10 feed posters','Caption copywriting','Post scheduling and publishing','Comment and message replies']},
 {name:'Premium',price:'₹59,999',items:['30 feed posts per month','Meta ads','Pro caption copywriting','Content calendar planning','Competitor analysis','Monthly analytics report']}
];
function packageCard(p,i,group){return `<a class="package-card" href="#booking" data-package="${p.name}" data-package-group="${group}"><span>0${i+1}</span><h4>${p.name}</h4><b>${p.price}</b><ul>${p.items.map(item=>`<li>${item}</li>`).join('')}</ul><i>Enquire about this package ↗</i></a>`}
document.querySelector('#wedding-packages').innerHTML=wedding.map((p,i)=>packageCard(p,i,'Wedding')).join('');
document.querySelector('#event-packages').innerHTML=other.map((p,i)=>packageCard(p,i,'Event')).join('');
document.querySelector('#social-packages').innerHTML=social.map((p,i)=>packageCard(p,i,'Social Media')).join('');
const filterNames=['All',...services.map(s=>s.name),'PhotoShoots Folder'];document.querySelector('#filters').innerHTML=filterNames.map((n,i)=>`<button class="filter${i===0?' active':''}" data-filter="${n}">${n}</button>`).join('');
const photoshootCover=assetUrl('PhotoShoots/WhatsApp%20Image%202026-10-01%20at%2012.50.58%20PM.jpeg');const galleryItems=[...services.flatMap(s=>s.files.slice(0,s.name==='Dress Shop'?3:2).map((f,i)=>({service:s.name,src:assetUrl(`video/${encodeURIComponent(browserVideo(f))}`),poster:poster(s),title:i===0?s.name:`${s.name} \u00b7 ${String(i+1).padStart(2,'0')}`}))),{service:'Gym',src:assetUrl('video/IMG_6664.mp4'),poster:assetUrl('image/IMG_5280.PNG'),title:'Gym'},{service:'Kavitha Jewellers',src:assetUrl('video/IMG_6674.MP4'),poster:assetUrl('image/IMG_5280.PNG'),title:'Kavitha Jewellers'},...['Afrin Cars','Ezhil cars','Golden Car Decors'].map(title=>({service:'Car Decors',src:assetUrl(`video/${encodeURIComponent(title)}.MP4`),poster:assetUrl('image/IMG_5280.PNG'),title})),{service:'PhotoShoots Folder',kind:'album',src:photoshootCover,poster:photoshootCover,title:'PhotoShoots'}];
const gallery=document.querySelector('#gallery');function renderGallery(filter='All'){const items=filter==='All'?galleryItems:galleryItems.filter(x=>x.service===filter);gallery.innerHTML=items.map((x,i)=>x.kind==='album'?`<article class="video-reel album-reel"><a class="gallery-item album-item" href="photoshoots.html" style="--poster:url('${x.poster}')" aria-label="Open PhotoShoots Folder photo gallery"><img class="album-cover" src="${x.src}" alt="PhotoShoots Folder preview" loading="lazy"><span class="gallery-overlay"><b>OPEN PHOTO GALLERY &#8599;</b><i>VIEW THE PHOTOS</i></span></a><div class="reel-caption"><span>${String(i+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}</span><b>PhotoShoots Folder</b><small>PHOTO GALLERY</small></div></article>`:`<article class="video-reel ${i===0?'reel-featured':''}"><div class="gallery-item play-media" style="--poster:url('${x.poster}')" data-poster="${x.poster}" data-src="${x.src}" data-title="${x.title}" role="group" aria-label="${x.title} video"><span class="poster-label">${x.service}<small>MEDIA SPACE &#183; VIDEO ${String(i+1).padStart(2,'0')}</small></span><button class="play-icon" type="button" aria-label="Play ${x.title} video">&#9654;</button><span class="gallery-overlay"><b>${x.title}</b><i>${x.service} &nbsp;&#183;&nbsp; PLAY FILM</i></span></div><div class="reel-caption"><span>${String(i+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}</span><b>${x.title}</b><small>${x.service}</small></div></article>`).join('');observePreviews(gallery)}
renderGallery();document.querySelector('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderGallery(b.dataset.filter)});
const form=document.querySelector('#booking-form'), eventSelect=form.elements.event, pkg=form.elements.package;
const enquiryPackageChoices=document.querySelector('#enquiry-package-choices');
function renderEnquiryPackageChoices(){const card=(p,i,group)=>`<button class="enquiry-package-option${pkg.value===p.name?' selected':''}" type="button" data-package="${p.name}" data-event="${group}"><span>${group.toUpperCase()} · 0${i+1}</span><b>${p.name}</b><strong>${p.price}</strong></button>`;const groups=[['Wedding',wedding],['Event',other],['Social Media',social]];enquiryPackageChoices.innerHTML=groups.map(([group,plans])=>`<div class="enquiry-package-group"><div class="enquiry-package-heading"><b>${group} packages</b><span>Choose one</span></div><div class="enquiry-package-options">${plans.map((p,i)=>card(p,i,group)).join('')}</div></div>`).join('')}
renderEnquiryPackageChoices();enquiryPackageChoices.addEventListener('click',e=>{const b=e.target.closest('[data-package]');if(!b)return;if(b.dataset.event==='Wedding')eventSelect.value='Wedding';else if(b.dataset.event==='Event'&&!['Birthday','Puberty','Baby Shower','Ear Piercing'].includes(eventSelect.value))eventSelect.value='Birthday';else if(b.dataset.event==='Social Media')eventSelect.value='Other';updatePackages();pkg.value=b.dataset.package;renderEnquiryPackageChoices()});
function updatePackages(){const ev=eventSelect.value, plans=ev==='Wedding'?wedding:['Birthday','Puberty','Baby Shower','Ear Piercing'].includes(ev)?other:ev==='Other'?social:[];const old=pkg.value;pkg.replaceChildren(new Option(plans.length?'Choose a package':'No package required',''));plans.forEach(p=>pkg.add(new Option(`${p.name} — ${p.price}`,p.name)));pkg.required=plans.length>0;document.querySelector('#package-field').classList.toggle('is-optional',!plans.length);if(plans.some(p=>p.name===old))pkg.value=old}
eventSelect.addEventListener('change',()=>{updatePackages();renderEnquiryPackageChoices()});pkg.addEventListener('change',renderEnquiryPackageChoices);updatePackages();renderEnquiryPackageChoices();
document.querySelectorAll('.package-card').forEach(c=>c.addEventListener('click',()=>{const p=c.dataset.package;eventSelect.value=c.dataset.packageGroup==='Wedding'?'Wedding':c.dataset.packageGroup==='Social Media'?'Other':'Birthday';updatePackages();pkg.value=p;renderEnquiryPackageChoices()}));
document.querySelectorAll('.service-link').forEach(a=>a.addEventListener('click',()=>{form.dataset.selectedService=a.dataset.service;const box=form.elements.message;box.placeholder=`Anything else we should know about ${a.dataset.service}?`}));
const today=new Date();form.elements.date.min=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);
const mediaLightbox=document.querySelector('#mediaLightbox'),lightboxVideo=document.querySelector('#mediaLightboxVideo');let mediaReturnFocus=null;
function openMediaLightbox(tile){mediaReturnFocus=tile.querySelector('.play-icon')||tile;document.querySelectorAll('.play-media video').forEach(video=>video.pause());lightboxVideo.src=tile.dataset.src;lightboxVideo.poster=tile.dataset.poster||'';lightboxVideo.muted=false;lightboxVideo.loop=false;lightboxVideo.controls=true;lightboxVideo.setAttribute('aria-label',tile.dataset.title||'Media Space video');mediaLightbox.hidden=false;mediaLightbox.setAttribute('aria-hidden','false');document.body.classList.add('media-viewer-open');mediaLightbox.querySelector('.media-lightbox-close').focus();if(mediaLightbox.requestFullscreen){const fullscreenRequest=mediaLightbox.requestFullscreen();fullscreenRequest?.catch(()=>{});}lightboxVideo.play().catch(()=>{});}
function closeMediaLightbox(){if(mediaLightbox.hidden)return;lightboxVideo.pause();lightboxVideo.removeAttribute('src');lightboxVideo.load();mediaLightbox.hidden=true;mediaLightbox.setAttribute('aria-hidden','true');document.body.classList.remove('media-viewer-open');if(document.fullscreenElement===mediaLightbox)document.exitFullscreen?.().catch(()=>{});mediaReturnFocus?.focus?.();document.querySelectorAll('.play-media video').forEach(video=>{const rect=video.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight&&rect.right>0&&rect.left<innerWidth)video.play().catch(()=>{});});}
document.addEventListener('click',event=>{const tile=event.target.closest('.play-media');if(!tile)return;event.preventDefault();openMediaLightbox(tile);});
mediaLightbox.querySelector('.media-lightbox-close').addEventListener('click',closeMediaLightbox);
mediaLightbox.addEventListener('click',event=>{if(event.target===mediaLightbox)closeMediaLightbox();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!mediaLightbox.hidden)closeMediaLightbox();});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&!mediaLightbox.hidden)closeMediaLightbox();});
if('scrollRestoration'in history)history.scrollRestoration='manual';window.scrollTo(0,0);
document.documentElement.dataset.theme='dark';
const menu=document.querySelector('.menu-toggle'), nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
function openWhatsApp(message,status){status.textContent='Opening WhatsApp to continue your enquiry.';window.open(`https://wa.me/919944367651?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));if(form.dataset.selectedService)data.service=form.dataset.selectedService;openWhatsApp(["Media Space booking enquiry",...Object.entries(data).map(([key,value])=>`${key}: ${value}`)].join("\n"),form.querySelector('.form-status'));});
const contactForm=document.querySelector('#contact-form');contactForm.addEventListener('submit',e=>{e.preventDefault();if(!contactForm.reportValidity())return;const payload=Object.fromEntries(new FormData(contactForm));const message=["Media Space message enquiry",...Object.entries(payload).filter(([key,value])=>key!=="website"&&value).map(([key,value])=>`${key}: ${value}`)].join("\n");openWhatsApp(message,contactForm.querySelector('.form-status'));});
document.querySelector('#year').textContent=new Date().getFullYear();
const loadScreen=document.querySelector('#load-screen'),loaderFilm=loadScreen.querySelector('.loader-film'),loaderBackdrop=loadScreen.querySelector('.loader-film-backdrop'),loaderEndLogo=loadScreen.querySelector('.loader-end-logo');let pageReady=document.readyState==='complete',filmReady=false,loaderFinished=false;function finishLoading(){if(loaderFinished||!pageReady||!filmReady)return;loaderFinished=true;document.body.classList.add('ready');loaderFilm.classList.add('video-ending');loaderBackdrop.classList.add('video-ending');const start=loaderEndLogo.getBoundingClientRect(),target=document.querySelector('.brand img').getBoundingClientRect();loaderEndLogo.classList.add('moving-to-header');loaderEndLogo.animate([{left:`${start.left}px`,top:`${start.top}px`,width:`${start.width}px`,height:`${start.height}px`,transform:'none',opacity:0,offset:0},{left:`${start.left}px`,top:`${start.top}px`,width:`${start.width}px`,height:`${start.height}px`,transform:'none',opacity:1,offset:.12},{left:`${target.left}px`,top:`${target.top}px`,width:`${target.width}px`,height:`${target.height}px`,transform:'none',opacity:1,offset:.78},{left:`${target.left}px`,top:`${target.top}px`,width:`${target.width}px`,height:`${target.height}px`,transform:'none',opacity:0,offset:1}],{duration:1050,easing:'cubic-bezier(.72,0,.24,1)',fill:'forwards'});setTimeout(()=>{loadScreen.classList.add('loaded');setTimeout(()=>loadScreen.remove(),700)},1050)}if(pageReady){}else window.addEventListener('load',()=>{pageReady=true;finishLoading()},{once:true});loaderFilm.addEventListener('ended',()=>{filmReady=true;finishLoading()},{once:true});loaderFilm.addEventListener('error',()=>{filmReady=true;finishLoading()},{once:true});const filmFallback=setTimeout(()=>{filmReady=true;finishLoading()},4500);loaderFilm.addEventListener('ended',()=>clearTimeout(filmFallback),{once:true});Promise.all([loaderFilm.play().catch(()=>{}),loaderBackdrop.play().catch(()=>{})]);




